### ISSUE TITLE
kills jupyter kernel

### ISSUE THREAD

**Issue by LiYunyang** [toshiyan/cmblensplus#1]
When calling some functions from a jupyter notebook, for example `curvedsky.norm_rot.qeb`, it says "The kernel appears to have died. It will restart automatically."
The same function works fine when called from a `.py` script.

**Comment by toshiyan** [comment]
My notebook works, so I guess some issue in your setup of Jupyter notebook. Please check memory, etc.

**Comment by LiYunyang** [comment]
I think it is the `stop` statement that causes the issue.  The kernel crashes every time `if (OCT(l)==0d0) stop 'error (norm_rot.qtb): observed clee is zero'` is triggered.
