### ISSUE TITLE
Bispectrum for flatsky 

### ISSUE THREAD

**Issue by mrhossen38** [toshiyan/cmblensplus#2]
Hi Toshiya,
Your code seems interesting to me. I found for `curvedsky` there is a function `curvedsky.bispec.bispec_norm(bn,bp,bstype='equi')`, I think one can compute other configurations  of bispectrum by changing the parameter `bstype`. Is there any function/ parameter for `flatsky` approximation like this? I have seen that for `flatsky` - the condition of computing Equilateral shape is `bfs=np.array((bf1,bf1,bf1))`, how one can modify this condition to calculate other bispectrum configurations (for example - isosceles, squeezed, etc)? Thanks.

**Comment by toshiyan** [comment]
The bispectrum code (flatsky.bispec.bispec_norm_1d) computes the binned bispectrum for a given set of the multipole range of three legs. For example, bfs = np.array((bf1,bf1,bf1)) specifies that all of three legs has the same multipole range. If you want to compute the squeezed case, defining bfs = np.array((sb0,bf1,bf1)) will give a squeezed limit bispectrum with sb0 the multipole bin of the longest leg, respectively. sb0 is given by e.g. sb0 = array of bf1[0] with the same length as bf1

**Comment by mrhossen38** [comment]
Thanks a lot, it really helps.
